Reviews from mentor
summerlightningman/dsr-l6-news pull request #1
Opened 2022-05-24 12:23 UTC by summerlightningman

2022-05-24 12:24 UTC, koshkinoko-hana commented on src/components/auth-page/auth-page.styled.tsx
> +  height: 100vh;
test

2022-05-25 18:32 UTC, koshkinoko-hana requested changes

2022-05-25 18:32 UTC, koshkinoko-hana commented on .idea/.gitignore
> -# Default ignored files
файлы идеи обычно добавляются в гитигнор, чтобы в проекте они не лежали, разрабы банально могут разными ide пользоваться)

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/auth-page/sign-up-form/sign-up-form.tsx
> +    // const initialVales: FormFields = {firstName: '', secondName: '', lastName: '', phone: '0 - 000 - 000 - 00 - 00', showFirstName: true, showLastname: true, showPhone: true};
это что такое?) не дочистил?))

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/all-news-list/all-news-list.tsx
> +    const {offset, limit} = useAppSelector(state => state.news);
как правило, создают отдельные селекторы для разных частей стора

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/new-post/new-post.tsx
> +    // @ts-ignore
это зачем?

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/new-post/tag.styled.tsx
> +  & > button {
Такие селекторы не очень хорошо работают (в смысле медленно), лучше отдельный класс на это заводить. Хотя все грешат этим, когда мы юзаем стайлд-компоненты)

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/new-post/tag.styled.tsx
> +  color: ${darkPink};
Я заметила, что ты много где такие константы юзаешь. Есть такая фича как themeProvider https://styled-components.com/docs/advanced
кажется она тут была бы очень уместна

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/news-body.styled.tsx
> +export const newsBodyWidth = '1200px';
Ты её ещё где-то юзаешь? тогда почему она тут а не в общих константах?

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/news-list-item/news-publication-status.styled.tsx
> +  line-height: 39px;
прикольная цифра, откуда она такая странная?)
Вообще кстати по хорошему все цифры выносятся в константы. Это не призыв к исправлению, просто на будущее. Это делается для того, чтобы если нужно поменять размеры шрифтов/кнопок/итд, это можно было сделать в одном месте, и все выглядело идентично

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/news-list-item/news-read-status.styled.tsx
> +  color: #828282;
какие то цвета ты выносишь в константы, а другие нет) хотя вот эту ты ещё как минимум в одном месте юзаешь

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/news-list-item/news-tag-list.styled.tsx
> +  font-family: 'Inter', sans-serif;
фонт лучше выставить в общем месте, какие-то глобальные стили сделать

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/news-navbar/news-navbar.tsx
> +    const path = window.location.pathname.replace('/', '');
это что за магия?)

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/news-page.tsx
> +    const navbar = useMemo(() => getNavbarByRole(user?.role || Role.READER), [user?.role]);
повторяющийся код

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/sub-news-list/sub-news-list.tsx
> +                            key={post.header + post.description + post.tags}
так нужно? какая цель? в крайнем случае можно было взять индекс из map)

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/tag-list/new-tag/new-tag.tsx
> +                ({
мне кажется, такие штуки стоило выносить в отдельные компоненты, выглядит слегка громоздко

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/tag-list/tag-list-item/tag-list-item.tsx
> +        const tags = user.tags.includes(tag) ? user.tags.filter(_ => _ !== tag) : [...user.tags, tag];
неужели эта переменная не заслужила своего названия?) типа item хотя бы)

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/news-page/tag-list/tag-list.tsx
> +        switch (status) {
Кажется вот эту штуку я вижу уже второй раз. Это значит, что она должна была быть вынесена в отдельный компонент

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/styled/global.tsx
> +    * {
медленный селектор )

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/components/styled/select.styled.tsx
> +  font-family: "Franklin Gothic Heavy", sans-serif;
Уже третий шрифт) ну ладно я уже придираюсь)

2022-05-25 18:32 UTC, koshkinoko-hana commented on src/http.ts
> +export const corsHeaders = {
мб стоило общую функцию написать, которая все эти хедеры добавит и её вызывать?

2022-05-26 14:10 UTC, summerlightningman commented on src/components/news-page/new-post/new-post.tsx
> +    // @ts-ignore
Тайпскрипт не замечает, что я у styled-component'а меняю селектор на form и считает, что я не могу обратиться к атрибуту onSubmit

2022-05-26 14:11 UTC, summerlightningman commented on src/components/news-page/news-body.styled.tsx
> +export const newsBodyWidth = '1200px';
не получалось корректно сделать ширину родителя для дочерних блоков, убрал

2022-05-26 14:12 UTC, summerlightningman commented on src/components/news-page/news-list-item/news-publication-status.styled.tsx
> +  line-height: 39px;
Фигма такую выдал :)

2022-05-26 14:12 UTC, summerlightningman commented on src/components/news-page/news-list-item/news-read-status.styled.tsx
> +  color: #828282;
не знал, подумаю, когда буду ковырять themeProvider

2022-05-26 14:14 UTC, summerlightningman commented on src/components/auth-page/sign-up-form/sign-up-form.tsx
> +    // const initialVales: FormFields = {firstName: '', secondName: '', lastName: '', phone: '0 - 000 - 000 - 00 - 00', showFirstName: true, showLastname: true, showPhone: true};
угу, сча почищу

2022-05-26 14:39 UTC, merged